from .nodes.load_model import NODE_CLASS_MAPPINGS as LOAD_MODEL_NODE_CLASS_MAPPINGS
from .nodes.load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_MODEL_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.sam3_interactive import NODE_CLASS_MAPPINGS as INTERACTIVE_NODE_CLASS_MAPPINGS
from .nodes.sam3_interactive import (
    NODE_DISPLAY_NAME_MAPPINGS as INTERACTIVE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.sam3_interactive import _api_segment_one
from .nodes.sam3_video_nodes import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS
from .nodes.sam3_video_nodes import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.segmentation import NODE_CLASS_MAPPINGS as SEGMENTATION_NODE_CLASS_MAPPINGS
from .nodes.segmentation import NODE_DISPLAY_NAME_MAPPINGS as SEGMENTATION_NODE_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOAD_MODEL_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SEGMENTATION_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(INTERACTIVE_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_MODEL_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SEGMENTATION_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INTERACTIVE_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"
ROUTES = [
    {"method": "POST", "path": "/sam3/interactive_segment_one", "handler": _api_segment_one},
]

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY", "ROUTES"]
